const PLAYLISTS = {
  "adda-classics": {
    name: "Adda Classics",
    songs: [
      { file: "music/adda-classics/salamat.opus", id: "VYcnmCrp8ug", title: "Salamat", artist: "Classic Hindi" },
      { file: "music/adda-classics/saaz-dil-chhed.opus", id: "yj5XEsVtOjE", title: "Saaz E Dil Chhed De", artist: "Classic Hindi" },
      { file: "music/adda-classics/sarphira-sa-hai.opus", id: "Sl3b-svF_V8", title: "Sarphira Sa Hai Dil", artist: "Classic Hindi" },
      { file: "music/adda-classics/such-keh-raha.opus", id: "3PQXtca7-24", title: "Such Keh Raha Hai", artist: "Classic Hindi" },
      { file: "music/adda-classics/saudebaazi.opus", id: "DY_nQgYCegI", title: "Saudebaazi", artist: "Classic Hindi" },
      { file: "music/adda-classics/mujhe-peene-do.opus", id: "tOXMlseYc7E", title: "Mujhe Peene Do", artist: "Classic Hindi" },
      { file: "music/adda-classics/mere-sanam.opus", id: "y2HspfsTRWY", title: "Mere Sanam", artist: "Classic Hindi" },
      { file: "music/adda-classics/noor-khuda.opus", id: "JJ5r5Z6G2Zo", title: "Noor E Khuda", artist: "Classic Hindi" },
      { file: "music/adda-classics/rabba-mehar-kari.opus", id: "7zEx0AJguSM", title: "Rabba Mehar Kari", artist: "Classic Hindi" },
      { file: "music/adda-classics/pardesi-pardesi.opus", id: "ulgolPYH5EE", title: "Pardesi Pardesi", artist: "Classic Hindi" },
      { file: "music/adda-classics/tune-jo-na.opus", id: "dTu5dTEzVM4", title: "Tune Jo Na Kaha", artist: "Classic Hindi" },
      { file: "music/adda-classics/tujhe-yaad-na.opus", id: "zf-hzOlou9k", title: "Tujhe Yaad Na Meri Ayee", artist: "Classic Hindi" },
      { file: "music/adda-classics/yeh-dil-deewana.opus", id: "KUjswKk5vuM", title: "Yeh Dil Deewana", artist: "Classic Hindi" },
      { file: "music/adda-classics/zakhm-dete-ho.opus", id: "KNYqXr3wvDs", title: "Zakhm Dete Ho", artist: "Classic Hindi" },
      { file: "music/adda-classics/yeh-jism.opus", id: "xycd6Kgk27c", title: "Yeh Jism", artist: "Classic Hindi" },
      { file: "music/adda-classics/long-time-no.opus", id: "fxwQ2FpF9ac", title: "Long Time No See", artist: "Classic Hindi" },
      { file: "music/adda-classics/sun-le-dastan.opus", id: "CzMAMit60h8", title: "Sun Le Dastan Yun Na Sata", artist: "Classic Hindi" },
      { file: "music/adda-classics/tujhe-kitna-chahne.opus", id: "A2IGDsD-dLF8", title: "Tujhe Kitna Chahne Lage", artist: "Classic Hindi" },
      { file: "music/adda-classics/tu-hai-kahan.opus", id: "AX6OrbgS8lI", title: "Tu Hai Kahan", artist: "Classic Hindi" },
      { file: "music/adda-classics/tu-chahiye.opus", id: "zuvla6ABKbs", title: "Tu Chahiye", artist: "Classic Hindi" },
      { file: "music/adda-classics/baharon-phool-barsao.opus", id: "McP9D114BfU", title: "Baharon Phool Barsao", artist: "Classic Hindi" },
      { file: "music/adda-classics/baar-baar-tohe.opus", id: "trQjxqvp6SY", title: "Baar Baar Tohe Kya Samjhaye", artist: "Classic Hindi" },
      { file: "music/adda-classics/chitta.opus", id: "CJq1hGSO89A", title: "Chitta", artist: "Classic Hindi" },
      { file: "music/adda-classics/ek-din-aap.opus", id: "2qjjKBaVHYE", title: "Ek Din Aap Yun Hum Se Mil Jaenge", artist: "Classic Hindi" },
      { file: "music/adda-classics/ek-dilruba-hai.opus", id: "UgrS_B53Yc", title: "Ek Dilruba Hai", artist: "Classic Hindi" },
      { file: "music/adda-classics/aam-chhum-taam.opus", id: "J3czXkNA5_E", title: "Aam Chhum Taam Chhum", artist: "Classic Hindi" },
      { file: "music/adda-classics/aaja-na-tere.opus", id: "mmA9Wrp5UNs", title: "Aaja Na Tere Bin", artist: "Classic Hindi" },
      { file: "music/adda-classics/aane-se-uske.opus", id: "4qwFpKmYH4k", title: "Aane Se Uske", artist: "Classic Hindi" },
      { file: "music/adda-classics/ankhiyon-ke-jharokhon.opus", id: "KqpIIaCJggY", title: "Ankhiyon Ke Jharokhon Se", artist: "Classic Hindi" },
      { file: "music/adda-classics/aap-mujhe-achchhe.opus", id: "Zt0KVVVNxA4", title: "Aap Mujhe Achchhe Lagne Lage", artist: "Classic Hindi" },
      { file: "music/adda-classics/kabhi-tumhe.opus", id: "ByIZIKFmHOA", title: "Kabhi Tumhe", artist: "Classic Hindi" },
      { file: "music/adda-classics/jo-tu-na.opus", id: "6DtPF9W3ejI", title: "Jo Tu Na Mila", artist: "Classic Hindi" },
      { file: "music/adda-classics/kya-loge-tum.opus", id: "cAMHx-m9oh8", title: "Kya Loge Tum", artist: "Classic Hindi" },
      { file: "music/adda-classics/mere-paas-tum.opus", id: "oyYL8bNJVh4", title: "Mere Paas Tum Ho", artist: "Classic Hindi" },
      { file: "music/adda-classics/mar-jaayen.opus", id: "fVZuAgPJuW4", title: "Mar Jaayen", artist: "Classic Hindi" },
      { file: "music/adda-classics/hasi.opus", id: "oyaudgo5_8Y", title: "Hasi", artist: "Classic Hindi" },
      { file: "music/adda-classics/goodbye.opus", id: "B2cNnvbu3Vc", title: "Goodbye", artist: "Classic Hindi" },
      { file: "music/adda-classics/hue-hum-jinke.opus", id: "IoFFQ_4gUu0", title: "Hue Hum Jinke Liye Barbad", artist: "Classic Hindi" },
      { file: "music/adda-classics/husn-hai-ya.opus", id: "Spa9cc-QakI", title: "Husn Hai Ya Koi Qayamat Hai", artist: "Classic Hindi" },
      { file: "music/adda-classics/hungama-ho-gaya.opus", id: "CEs3AeV0di0", title: "Hungama Ho Gaya", artist: "Classic Hindi" },
    ],
  },
  "chai-baatein": {
    name: "Chai & Baatein",
    songs: [
      { file: "music/chai-baatein/main-hun-gaon.opus", id: "wDVmpv4thR4", title: "Main Hun Gaon Ki Gori", artist: "Classic Hindi" },
      { file: "music/chai-baatein/man-mera-udta.opus", id: "eUVCUg_SY98", title: "Man Mera Udta Jaye", artist: "Classic Hindi" },
      { file: "music/chai-baatein/matwali-ankhowale.opus", id: "uEnNWjVFLv8", title: "Matwali Ankhowale", artist: "Classic Hindi" },
      { file: "music/chai-baatein/main-chali-main.opus", id: "szFxM9KBNMA", title: "Main Chali Main Chali", artist: "Classic Hindi" },
      { file: "music/chai-baatein/leja-meri-duayen.opus", id: "mYD_P7g7qR8", title: "Leja Meri Duayen", artist: "Classic Hindi" },
      { file: "music/chai-baatein/maar-dalega-dard.opus", id: "f4y5rGB0NgE", title: "Maar Dalega Dard E Jigar", artist: "Classic Hindi" },
      { file: "music/chai-baatein/main-bhookha.opus", id: "VnvGGPolgu8", title: "Main Bhookha", artist: "Classic Hindi" },
      { file: "music/chai-baatein/meine-kaha-tumse.opus", id: "wPKCZrHkQdc", title: "Meine Kaha Tumse", artist: "Classic Hindi" },
      { file: "music/chai-baatein/phoolon-ki-sej.opus", id: "EGSL5Mhl3o0", title: "Phoolon Ki Sej", artist: "Classic Hindi" },
      { file: "music/chai-baatein/woh-jab-yaad.opus", id: "4bgdcTbb6uk", title: "Woh Jab Yaad Aaye", artist: "Classic Hindi" },
      { file: "music/chai-baatein/yaad-suhani-teri.opus", id: "2aWOWy9Fj-k", title: "Yaad Suhani Teri", artist: "Classic Hindi" },
      { file: "music/chai-baatein/nazar-ka-jhuk.opus", id: "obxDewuthro", title: "Nazar Ka Jhuk Jana", artist: "Classic Hindi" },
      { file: "music/chai-baatein/meri-pyari-bindu.opus", id: "Zr_enRRcyuw", title: "Meri Pyari Bindu", artist: "Classic Hindi" },
      { file: "music/chai-baatein/mohabbat-jisko-kehte.opus", id: "6hdz1ddVhxU", title: "Mohabbat Jisko Kehte Hain", artist: "Classic Hindi" },
      { file: "music/chai-baatein/naseeb-dar-pe.opus", id: "rnMtmpsaBqM", title: "Naseeb Dar Pe Tere", artist: "Classic Hindi" },
      { file: "music/chai-baatein/lage-nahi-mora.opus", id: "_4ITncpWB9g", title: "Lage Nahi Mora Jiya", artist: "Classic Hindi" },
      { file: "music/chai-baatein/chanda-sitare-bindiya.opus", id: "9VXk9lUYpd0", title: "Chanda Sitare Bindiya Tumhari", artist: "Classic Hindi" },
      { file: "music/chai-baatein/dekh-liya-maine.opus", id: "lYcnZTPIxn4", title: "Dekh Liya Maine Kismat Ka Tamasha", artist: "Classic Hindi" },
      { file: "music/chai-baatein/dekha-na-haye.opus", id: "fF3q0_1hwLI", title: "Dekha Na Haye Re", artist: "Classic Hindi" },
      { file: "music/chai-baatein/chaman-mein-rakhe.opus", id: "ohdVO5AlEXI", title: "Chaman Mein Rakhe Veerana", artist: "Classic Hindi" },
      { file: "music/chai-baatein/bachpan-ke-din.opus", id: "M3mNpPbJeFc", title: "Bachpan Ke Din Bhula Na Dena", artist: "Classic Hindi" },
      { file: "music/chai-baatein/bhai-batur.opus", id: "RIXVQrS5s8", title: "Bhai Batur", artist: "Classic Hindi" },
      { file: "music/chai-baatein/bol-radha-bol.opus", id: "sGZfEqColpM", title: "Bol Radha Bol", artist: "Classic Hindi" },
      { file: "music/chai-baatein/dil-chahe-kisi.opus", id: "mFe097V0ouY", title: "Dil Chahe Kisi Se Pyar Karoon", artist: "Classic Hindi" },
      { file: "music/chai-baatein/kabhi-jo-bhoolna.opus", id: "PK6EogtaalY", title: "Kabhi Jo Bhoolna Chahun", artist: "Classic Hindi" },
      { file: "music/chai-baatein/kehna-hai.opus", id: "Ewj3fShfZow", title: "Kehna Hai", artist: "Classic Hindi" },
      { file: "music/chai-baatein/khush-rahe-tu.opus", id: "ayGc5A6X9Go", title: "Khush Rahe Tu Sada", artist: "Classic Hindi" },
      { file: "music/chai-baatein/head-ya-tail.opus", id: "oS7cIJvoLWk", title: "Head Ya Tail", artist: "Classic Hindi" },
      { file: "music/chai-baatein/ek-baat-poochhta.opus", id: "3wCxw9pDITo", title: "Ek Baat Poochhta Hoon", artist: "Classic Hindi" },
      { file: "music/chai-baatein/gori-tera-gaon.opus", id: "vejr2_PXVQo", title: "Gori Tera Gaon Bada Pyara", artist: "Classic Hindi" },
      { file: "music/chai-baatein/hansta-hua-noorani.opus", id: "5KkkDRCj3l8", title: "Hansta Hua Noorani Chehra", artist: "Classic Hindi" },
    ],
  },
  "lucknow-shaam": {
    name: "Lucknow Shaam",
    songs: [
      { file: "music/lucknow-shaam/tere-bina-dil.opus", id: "LOcM2YEbUo4", title: "Tere Bina Dil Lagta Nahi", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/tere-mere-beech.opus", id: "bSODb0x2plA", title: "Tere Mere Beech Mein", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/tauba-tauba-ho.opus", id: "7OTFv--C-YM", title: "Tauba Tauba Ho Tauba", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/savaiyaa-chhota-sa.opus", id: "bT6bYr6lQ9o", title: "Savaiyaa Chhota Sa Saajan", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/sawan-ka-mahina.opus", id: "aSqwfhYAoxs", title: "Sawan Ka Mahina", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/titli-udi-ud.opus", id: "ob4vW-Il0tA", title: "Titli Udi Ud Jo Chali", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/woh-kaunsi-mushkil.opus", id: "9YHkf6sA-jU", title: "Woh Kaunsi Mushkil Hai", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/ye-gaya-wo.opus", id: "QR2ufDPheys", title: "Ye Gaya Wo Gaya", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/tumhi-ne-meri.opus", id: "1ixXI80LiI8", title: "Tumhi Ne Meri Zindagi Re", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/tu-kon-hai.opus", id: "sM7wbm6lWLE", title: "Tu Kon Hai Mera Kehde Balam", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/tu-tu-tu.opus", id: "BWBQ28FHrqU", title: "Tu Tu Tu Tara", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/deewana-dil-beqarar.opus", id: "OeFXppUkV48", title: "Deewana Dil Beqarar Tha", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/dilbara-jab-tera.opus", id: "aZNA3e0MxiM", title: "Dilbara Jab Tera Naam Liya", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/chura-ke-dil.opus", id: "Pu4o37QAHIg", title: "Chura Ke Dil Ban Rahe Ho Bhole", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/ab-mohabbat-mein.opus", id: "EfvxsPqhCgw", title: "Ab Mohabbat Mein Jo Pahle", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/chhan-chhan-payal.opus", id: "ulxky6wuXa8", title: "Chhan Chhan Payal Chhanke", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/jaa-raha-hai.opus", id: "PFEt4oAWl-0", title: "Jaa Raha Hai Kyon Deewane", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/mummy-mummy.opus", id: "8yoiLf_O8I4", title: "O Mummy Mummy", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/nazar-na-phero.opus", id: "ytzp9gpx3OI", title: "Nazar Na Phero Humse", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/maheki-maheki-thandi.opus", id: "cazcJ__xWKY", title: "O Maheki Maheki Thandi Hawa", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/jaago-sone-walo.opus", id: "McWljApC79c", title: "Jaago Sone Walo", artist: "Classic Hindi" },
      { file: "music/lucknow-shaam/jeenewale-muskura-ke.opus", id: "_ZDkPxU3KA8", title: "Jeenewale Muskura Ke Jee", artist: "Classic Hindi" },
    ],
  },
  "purani-yaadein": {
    name: "Purani Yaadein",
    songs: [
      { file: "music/purani-yaadein/kajre-badarwa-re.opus", id: "Gm0bYd5u024", title: "Kajre Badarwa Re", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/kahin-se-chali.opus", id: "ViY-lbX3yfo", title: "Kahin Se Chali Aa", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/itna-hai-tumse.opus", id: "Eq5aJPA19tU", title: "Itna Hai Tumse Pyar Mujhe", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/khoobsurat-haseena.opus", id: "xNDE3w0KdBk", title: "Khoobsurat Haseena", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/mere-pyar-aaja.opus", id: "_YgZAV8kRZg", title: "O Mere Pyar Aaja", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/koi-jab-raah.opus", id: "PRoeFUnx5K0", title: "Koi Jab Raah Na Paye", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/khuli-khuli-zulfon.opus", id: "S4Nb5CecDbM", title: "Khuli Khuli Zulfon Ko", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/ilahi-tu-sun.opus", id: "im-ViPIiA4o", title: "Ilahi Tu Sun Le Hamari Dua", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/aaj-mausam-ki.opus", id: "2m4uonSYw58", title: "Aaj Mausam Ki Masti Mein", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/aaj-hua-mera.opus", id: "JRSwynOgN2c", title: "Aaj Hua Mera Dil Matwala", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/aa-bhi-ja.opus", id: "4NppgimXvrM", title: "Aa Bhi Ja Rasiya", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/allah-jaane-main.opus", id: "V0cwfGazerc", title: "Allah Jaane Main Hoon Kaun", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/ghar-aaja-ghir.opus", id: "6tcQcf1zlC0", title: "Ghar Aaja Ghir Aaye Badra", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/ek-sawaal-hai.opus", id: "6tKQ4W5PwVI", title: "Ek Sawaal Hai Tumse", artist: "Classic Hindi" },
      { file: "music/purani-yaadein/chali-re-chali.opus", id: "HOvTXM4TjtQ", title: "Chali Re Chali Re Gori", artist: "Classic Hindi" },
    ],
  },
};

